---
name: freckle-app
version: 1.5.1.0
maintainer: Freckle Education
category: Utils
github: freckle/freckle-app
synopsis: Haskell application toolkit used at Freckle
description: Please see README.md

extra-doc-files:
  - README.md
  - CHANGELOG.md

extra-source-files:
  - package.yaml

flags:
  test-git:
    description: Run tests that run git commands
    manual: true
    default: true

dependencies:
  - base < 5

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: library
  dependencies:
    - Blammo
    - Glob
    - MonadRandom
    - aeson
    - bugsnag
    - bytestring
    - case-insensitive
    - conduit
    - containers
    - datadog
    - doctest
    - dotenv
    - ekg-core
    - envparse
    - errors
    - exceptions
    - extra
    - filepath
    - hashable
    - hspec >= 2.8.1
    - hspec-core >= 2.8.1
    - hspec-expectations-lifted
    - hspec-junit-formatter >= 1.1.0.1
    - http-client
    - http-conduit >= 2.3.5 # addToRequestQueryString
    - http-link-header
    - http-types
    - immortal
    - lens
    - memcache
    - monad-control
    - mtl
    - network-uri
    - path-pieces
    - persistent
    - persistent-postgresql
    - postgresql-simple
    - primitive
    - resource-pool
    - retry >= 0.8.1.0 # retryingDynamic
    - safe
    - scientist
    - semigroupoids
    - template-haskell
    - text
    - time
    - transformers
    - transformers-base
    - typed-process
    - unliftio
    - unliftio-core
    - unordered-containers
    - vector
    - wai
    - wai-extra
    - yaml
    - yesod-core

tests:
  spec:
    main: Main.hs
    source-dirs: tests
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N"
    dependencies:
      - Blammo
      - QuickCheck
      - aeson
      - bugsnag
      - bytestring
      - errors
      - freckle-app
      - hspec
      - http-types
      - lens
      - lens-aeson
      - memcache
      - postgresql-simple
      - unliftio
      - wai
      - wai-extra

  doctest:
    main: Main.hs
    source-dirs: doctest
    dependencies:
      - freckle-app

  gittest:
    main: Main.hs
    source-dirs: gittest
    dependencies:
      - freckle-app
      - directory
      - hspec
      - temporary
      - time
      - process
      - text
    when:
      - condition: flag(test-git)
        then:
          buildable: true
        else:
          buildable: false
