resolver: lts-19.31

extra-deps:
  - Blammo-1.0.2.2
  - bugsnag-1.0.0.1
  - bugsnag-wai-1.0.0.1
  - context-0.2.0.1
  - ekg-core-0.1.1.7
  - envparse-0.5.0
  - hspec-junit-formatter-1.1.0.2
  - memcache-0.3.0.1
  - monad-logger-aeson-0.3.0.2
  - monad-validate-1.2.0.1
  - scientist-0.0.0.0

ghc-options:
  "$locals": >-
    -fwrite-ide-info
    -Weverything
    -Wno-all-missed-specialisations
    -Wno-deriving-typeable
    -Wno-implicit-prelude
    -Wno-incomplete-uni-patterns
    -Wno-missed-specialisations
    -Wno-missing-export-lists
    -Wno-missing-exported-signatures
    -Wno-missing-import-lists
    -Wno-missing-local-signatures
    -Wno-missing-monadfail-instances
    -Wno-missing-safe-haskell-mode
    -Wno-monomorphism-restriction
    -Wno-partial-fields
    -Wno-prepositive-qualified-module
    -Wno-safe
    -Wno-unsafe
