resolver: lts-22.34
extra-deps:
  - Blammo-2.1.1.0
  - Blammo-wai-0.0.0.2
  - fast-logger-3.2.3
  - monad-validate-1.3.0.0
  - hs-opentelemetry-api-0.1.0.0
  - hs-opentelemetry-instrumentation-persistent-0.1.0.0
  - hs-opentelemetry-instrumentation-wai-0.1.0.0
  - hs-opentelemetry-sdk-0.0.3.6
  - hspec-junit-formatter-1.1.1.0

  # for hs-opentelemetry-sdk
  - hs-opentelemetry-exporter-otlp-0.0.1.5
  - hs-opentelemetry-propagator-b3-0.0.1.1
  - hs-opentelemetry-propagator-w3c-0.0.1.3

  # for hs-opentelemetry-exporter-otlp
  - hs-opentelemetry-otlp-0.0.1.0

  # for hs-opentelemetry-api
  - thread-utils-context-0.3.0.4

  # for thread-utils-context
  - thread-utils-finalizers-0.1.1.0

packages:
  - freckle-app
  - freckle-env
  - freckle-exception
  - freckle-http
  - freckle-kafka
  - freckle-memcached
  - freckle-otel
  - freckle-prelude
