resolver: lts-19.6

extra-deps:
  - hspec-junit-formatter-1.1.0.2
  - memcache-0.3.0.1
  - scientist-0.0.0.0
  - bugsnag-1.0.0.1
  - bugsnag-wai-1.0.0.1
  - github: freckle/ekg-core
    commit: 43aac16a0ac762b5997a62d0fbae96242d54fe14

ghc-options:
  "$locals": >-
    -fwrite-ide-info
    -Weverything
    -Wno-all-missed-specialisations
    -Wno-deriving-typeable
    -Wno-implicit-prelude
    -Wno-incomplete-uni-patterns
    -Wno-missed-specialisations
    -Wno-missing-export-lists
    -Wno-missing-exported-signatures
    -Wno-missing-import-lists
    -Wno-missing-local-signatures
    -Wno-missing-monadfail-instances
    -Wno-missing-safe-haskell-mode
    -Wno-monomorphism-restriction
    -Wno-partial-fields
    -Wno-prepositive-qualified-module
    -Wno-safe
    -Wno-unsafe
