name: persistent-sql-lifted
version: 0.1.0.0

maintainer: Freckle Education
category: Database
github: freckle/freckle-app
synopsis: Monad classes for running queries with Persistent and Esqueleto
description: |
  This package introduces two classes: MonadSqlBackend for monadic contexts in
  which a SqlBackend is available, and MonadSqlBackend for contexts in which we
  can execute a SQL transaction.

  Additionally, this package provides variants of query-running utilities from
  Persistent and Esqueleto which are concretized to use SqlBackend, generalized
  to a MonadSqlBackend m constraint rather than "ReaderT backend", and wrapped in
  checkpointCallStack so that exceptions will include call stacks.

extra-doc-files:
  - README.md
  - CHANGELOG.md

extra-source-files:
  - package.yaml

language: GHC2021

ghc-options:
  - -fignore-optim-changes
  - -fwrite-ide-info
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-local-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-prepositive-qualified-module
  - -Wno-safe
  - -Wno-unsafe

when:
  - condition: "impl(ghc >= 9.8)"
    ghc-options:
      - -Wno-missing-role-annotations
      - -Wno-missing-poly-kind-signatures

dependencies:
  - base < 5

default-extensions:
  - ExplicitNamespaces
  - FunctionalDependencies
  - GADTs
  - NoImplicitPrelude
  - NoMonomorphismRestriction

library:
  source-dirs: library
  dependencies:
    - annotated-exception
    - conduit
    - containers
    - esqueleto
    - mtl
    - persistent
    - text
    - unliftio-core
