name: freckle-app
version: 1.25.0.1

maintainer: Freckle Education
category: Utils
github: freckle/freckle-app
synopsis: Haskell application toolkit used at Freckle
description: Please see README.md

extra-doc-files:
  - README.md
  - CHANGELOG.md

extra-source-files:
  - package.yaml

language: GHC2021

ghc-options:
  - -fignore-optim-changes
  - -fwrite-ide-info
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-local-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-prepositive-qualified-module
  - -Wno-safe
  - -Wno-unsafe

when:
  - condition: "impl(ghc >= 9.8)"
    ghc-options:
      - -Wno-missing-role-annotations
      - -Wno-missing-poly-kind-signatures

dependencies:
  - base < 5

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DerivingVia
  - DerivingStrategies
  - GADTs
  - LambdaCase
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RecordWildCards
  - TypeFamilies

library:
  source-dirs: library
  dependencies:
    - Blammo
    - Blammo-wai
    - Glob
    - HUnit
    - MonadRandom
    - QuickCheck
    - annotated-exception
    - autodocodec
    - autodocodec-openapi3
    - aeson
    - bcp47
    - bugsnag >= 1.1.0.0 # Network.Bugsnag.MetaData
    - bytestring
    - case-insensitive
    - cassava
    - conduit
    - conduit-extra
    - containers
    - cookie
    - doctest
    - exceptions
    - faktory
    - freckle-env
    - freckle-exception
    - freckle-http
    - freckle-otel
    - freckle-prelude
    - freckle-stats
    - hs-opentelemetry-api
    - hs-opentelemetry-instrumentation-persistent
    - hs-opentelemetry-instrumentation-wai
    - hs-opentelemetry-sdk
    - hspec >= 2.8.1
    - hspec-core >= 2.8.1
    - hspec-expectations-lifted
    - hspec-junit-formatter >= 1.1.1.0 # Test.Hspec.JUnit.Formatter
    - http-client
    - http-types
    - immortal
    - lens
    - monad-control
    - monad-validate
    - mtl
    - nonempty-containers
    - openapi3
    - path-pieces
    - persistent
    - persistent-sql-lifted
    - persistent-postgresql
    - postgresql-simple
    - prettyprinter
    - primitive
    - resource-pool >= 0.4.0.0 # defaultPoolConfig, etc
    - resourcet
    - servant-server
    - scientist
    - semigroupoids
    - template-haskell
    - text
    - transformers
    - transformers-base
    - typed-process
    - unliftio
    - unordered-containers
    - vector
    - wai
    - wai-extra
    - yaml
    - yesod-core
    - yesod-test

tests:
  spec:
    main: Main.hs
    source-dirs: tests
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N"
    dependencies:
      - annotated-exception
      - Blammo
      - HUnit
      - QuickCheck
      - aeson
      - async
      - bugsnag
      - bytestring
      - cassava
      - conduit
      - freckle-app
      - freckle-exception
      - freckle-prelude
      - freckle-stats
      - hs-opentelemetry-api
      - hspec
      - http-types
      - monad-validate
      - nonempty-containers
      - path-pieces
      - persistent
      - postgresql-simple
      - servant-server
      - vector
      - wai
      - wai-extra

  doctest:
    main: Main.hs
    source-dirs: doctest
    dependencies:
      - freckle-app
