name: freckle-http
version: 0.0.0.0
maintainer: Freckle Education
category: Utils
github: freckle/freckle-app
synopsis: ...
description: Please see README.md

extra-doc-files:
  - README.md
  - CHANGELOG.md

extra-source-files:
  - package.yaml

language: GHC2021

ghc-options:
  - -fignore-optim-changes
  - -fwrite-ide-info
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-local-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-prepositive-qualified-module
  - -Wno-safe
  - -Wno-unsafe

when:
  - condition: "impl(ghc >= 9.8)"
    ghc-options:
      - -Wno-missing-role-annotations
      - -Wno-missing-poly-kind-signatures

dependencies:
  - base < 5

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DerivingVia
  - DerivingStrategies
  - DuplicateRecordFields
  - GADTs
  - LambdaCase
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedRecordDot
  - OverloadedStrings
  - RecordWildCards
  - TypeFamilies

library:
  source-dirs: library
  dependencies:
    - Glob
    - Blammo
    - aeson
    - annotated-exception
    - bytestring
    - case-insensitive
    - conduit
    - directory
    - errors
    - extra
    - filepath
    - freckle-memcached
    - hs-opentelemetry-api
    - hspec >= 2.8.1
    - http-client
    - http-conduit >= 2.3.5 # addToRequestQueryString
    - http-link-header
    - http-types
    - lens
    - lens-aeson
    - memcache
    - monad-logger
    - monad-validate
    - mtl
    - network-uri
    - retry >= 0.8.1.0 # retryingDynamic
    - safe
    - serialise
    - semigroupoids
    - text
    - time
    - transformers
    - unliftio
    - unordered-containers

tests:
  spec:
    main: Main.hs
    source-dirs: tests
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N"
    dependencies:
      - aeson
      - bytestring
      - freckle-http
      - hspec
      - hspec-expectations-json
      - hspec-expectations-lifted
      - http-types
      - lens
      - mtl
      - time
      - unordered-containers
      - zlib
