name: Build, test, and lint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # FrontRow.App.Version tests create commits
      - name: git config
        run: |
          actor=${{ github.actor }}
          git config --global user.email "$actor@users.noreply.github.com"
          git config --global user.name "$actor"

      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            ./.stack-work
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('stack.yaml') }}-
            ${{ runner.os }}-
      - uses: freckle/stack-action@v1
