name: CI

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: generate
        uses: freckle/stack-action/generate-matrix@v4
    outputs:
      stack-yamls: ${{ steps.generate.outputs.stack-yamls }}
      fail-fast: false

  test:
    needs: generate
    runs-on: ubuntu-latest
    services:
      memcached:
        image: memcached:1.6.14
        ports:
          - 11211:11211
        options: >-
          --health-cmd "bash -c 'echo >/dev/tcp/127.0.0.1/11211'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        stack-yaml: ${{ fromJSON(needs.generate.outputs.stack-yamls) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Install system libraries
        run: sudo apt-get install --assume-yes --no-install-recommends libpcre3 librdkafka-dev
      - uses: freckle/stack-action@v5
        env:
          OTEL_TRACES_EXPORTER: none
          STACK_YAML: ${{ matrix.stack-yaml }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/hlint-setup@v2
      - uses: haskell-actions/hlint-run@v2
        with:
          fail-on: warning
