name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stack-yaml:
          - stack.yaml           # ghc-8.10
          - stack-lts-16.31.yaml # ghc-8.8
          - stack-lts-14.27.yaml # ghc-8.6
          - stack-lts-12.26.yaml # ghc-8.4
      fail-fast: false

    steps:
      # Freckle.App.Version tests create commits
      - name: git config
        run: |
          actor=${{ github.actor }}
          git config --global user.email "$actor@users.noreply.github.com"
          git config --global user.name "$actor"

      - uses: actions/checkout@v2
      - uses: freckle/stack-cache-action@v2
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
      - uses: freckle/stack-action@v3
        with:
          stack-yaml: ${{ matrix.stack-yaml }}

  nightly:
    runs-on: ubuntu-latest

    steps:
      # Freckle.App.Version tests create commits
      - name: git config
        run: |
          actor=${{ github.actor }}
          git config --global user.email "$actor@users.noreply.github.com"
          git config --global user.name "$actor"

      - uses: actions/checkout@v2
      - uses: freckle/stack-cache-action@v2
        with:
          stack-yaml: stack-nightly.yaml
      - uses: freckle/stack-action@v3
        with:
          stack-yaml: stack-nightly.yaml
          stack-arguments: --resolver nightly

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rwe/actions-hlint-setup@v1
      - uses: rwe/actions-hlint-run@v2
        with:
          fail-on: warning
