name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # FrontRow.App.Version tests create commits
      - name: git config
        run: |
          actor=${{ github.actor }}
          git config --global user.email "$actor@users.noreply.github.com"
          git config --global user.name "$actor"

      - uses: actions/checkout@v2
      - uses: freckle/stack-cache-action@v1.0.1
      - uses: freckle/stack-action@main
        with:
          weeder: false
