name: CI

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      memcached:
        image: memcached:1.6.14
        ports:
          - 11211:11211
        options: >-
          --health-cmd "bash -c 'echo >/dev/tcp/127.0.0.1/11211'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        stack-yaml:
          - stack-nightly.yaml # ghc-9.4
          - stack.yaml # ghc-9.2
          - stack-lts-19.33.yaml # ghc-9.0
          - stack-lts-18.28.yaml # ghc-8.10
          # - stack-lts-16.31.yaml # ghc-8.8
          # - stack-lts-14.27.yaml # ghc-8.6
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Install rdkafka
        run: sudo apt-get install --assume-yes --no-install-recommends librdkafka-dev
      - uses: freckle/stack-cache-action@v2
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
      - uses: freckle/stack-action@v3
        with:
          stack-yaml: ${{ matrix.stack-yaml }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/hlint-setup@v2
      - uses: haskell/actions/hlint-run@v2
        with:
          fail-on: warning
