name: Release

on:
  push:
    branches: main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: tag
        uses: freckle/haskell-tag-action@v1
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

  release:
    needs: tag
    if: needs.tag.outputs.tag

    runs-on: ubuntu-latest

    env:
      HACKAGE_KEY: ${{ secrets.HACKAGE_UPLOAD_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install --assume-yes --no-install-recommends librdkafka-dev

      - name: "Build with Haddocks"
        uses: freckle/stack-action@v5
        with:
          test: false
          stack-build-arguments: --haddock --haddock-for-hackage

      # Upload using our oldest, tested resolver, to set the lowest lower bounds
      - name: "Release to Hackage"
        run: stack --stack-yaml stack-lts-20.26.yaml upload --pvp-bounds lower freckle-app

      - name: "Upload documentation"
        run: stack upload --documentation freckle-app
