name: Release

on:
  push:
    branches: main

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - freckle-app
          - freckle-env
          - freckle-kafka

    env:
      HACKAGE_KEY: ${{ secrets.HACKAGE_UPLOAD_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get install --assume-yes --no-install-recommends librdkafka-dev

      - id: tag
        uses: freckle/haskell-tag-action@v1
        with:
          package-yaml: ${{ matrix.package }}/package.yaml
          tag-prefix: ${{ matrix.package }}-v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.tag.outputs.tag
        name: "Build with Haddocks"
        uses: freckle/stack-action@v5
        with:
          test: false
          stack-build-arguments: --haddock --haddock-for-hackage

      - if: steps.tag.outputs.tag
        run: stack upload --pvp-bounds lower ${{ matrix.package }}
        env:
          STACK_YAML: stack-lts-20.26.yaml

      - if: steps.tag.outputs.tag
        name: "Upload documentation"
        run: stack upload --documentation ${{ matrix.package }}
