name: Release

on:
  push:
    branches: main

jobs:
  tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - freckle-app
          - freckle-env
          - freckle-exception
          - freckle-kafka
          - freckle-http
          - freckle-memcached
          - freckle-otel
          - freckle-prelude

    steps:
      - uses: actions/checkout@v4
      - id: tag
        uses: freckle/haskell-tag-action@v1
        with:
          package-yaml: ${{ matrix.package }}/package.yaml
          tag-prefix: ${{ matrix.package }}-v
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

  release:
    needs: tag
    if: needs.tag.outputs.tag

    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - freckle-app
          - freckle-env
          - freckle-exception
          - freckle-kafka
          - freckle-http
          - freckle-memcached
          - freckle-otel
          - freckle-prelude

        include:
          # Packages with system dependencies (librdkafka, libpq) need haddocks
          # built and uploaded manually.
          - package: freckle-kafka
            upload-haddocks: true
          - package: freckle-app
            upload-haddocks: true

    env:
      HACKAGE_KEY: ${{ secrets.HACKAGE_UPLOAD_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install --assume-yes --no-install-recommends librdkafka-dev

      - name: "Build with Haddocks"
        if: ${{ matrix.upload-haddocks }}
        uses: freckle/stack-action@v5
        with:
          test: false
          stack-build-arguments: --haddock --haddock-for-hackage

      # Upload using our oldest, tested resolver, to set the lowest lower bounds
      - name: "Release to Hackage"
        run: stack --stack-yaml stack-lts-20.26.yaml upload --pvp-bounds lower ${{ matrix.package }}

      - name: "Upload documentation"
        if: ${{ matrix.upload-haddocks }}
        run: stack upload --documentation ${{ matrix.package }}
